# https://github.com/marketplace/actions/delete-workflow-runs
name: Delete old workflow runs
on:
  schedule:
    - cron: "0 4 * * 1" # Weekly on Monday at 04:00
  # to allow manual triggering of the workflow from the GitHub Actions tab:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:

      - name: Delete successful runs of workflows without badges
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: dependabot|cleanup|releaseNuget|checkLinks
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: success


      - name: Keep the latest run of each badge workflow
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          delete_workflow_pattern: build.yml|docs.yml|test.yml
          keep_minimum_runs: 1

      - name: Delete failed runs of workflows without badges after 30 days
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: dependabot|cleanup|releaseNuget|checkLinks
          retain_days: 30
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: cancelled, failure, skipped
