name: Docs

# copied from https://fsprojects.github.io/FSharp.Formatting/zero-to-hero.html#Ship-it

# Trigger this Action when new code is pushed to the main branch
on:
  push:
    branches:
      - main

# We need some permissions to publish to Github Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - uses: actions/checkout@v4
      # Setup dotnet, please use a global.json to ensure the right SDK is used!
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      # Restore the local tools
      - name: Restore tools
        run: dotnet tool restore
      # Build the code for the API documentation
      - name: Build code
        run: dotnet build -c Release Str.sln

      # Copy README.md to docs folder as index.md //adde by Goswin
      - name: make README the index
        run: cp README.md docs/index.md
      # Copy LICENSE to docs folder
      - name: Copy LICENSE to docs
        run: cp LICENSE docs/LICENSE.md
      # Copy CHANGELOG.md to docs folder
      - name: Copy CHANGELOG to docs
        run: cp CHANGELOG.md docs/CHANGELOG.md

      # Generate the documentation files
      - name: Generate the documentation'
        run: dotnet fsdocs build --properties Configuration=Release
      # Upload the static files
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./output

  # GitHub Actions recommends deploying in a separate job.
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2